# Server
server:
  port: 80
  servlet:
    session:
      tracking-modes: cookie
  tomcat:
    mbeanregistry:
      enabled: true
# Database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/possystem?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: rhakqjsro12!

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
#        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

# MyBatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.hsj.force.domain

# File
file :
  dir : C:/force-project/force/src/main/resources/static/upload/

management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  server:
    port: 8080
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: "*"