CREATE TABLE `TCATEGORY`
(
    `CATEGORY_NO`    VARCHAR(100) NOT NULL COMMENT '카테고리번호',
    `CATEGORY_NAME`    VARCHAR(100) NOT NULL COMMENT '카테고리명',
    `PRIORITY`    DECIMAL NOT NULL COMMENT '우선순위',
    `USE_YN`    CHAR NOT NULL COMMENT '사용유무',
    `INSERT_ID`    VARCHAR(100) NOT NULL COMMENT '등록자',
    `INSERT_DATE`    DATETIME NOT NULL COMMENT '등록일자',
    `MODIFY_ID`    VARCHAR(100) NOT NULL COMMENT '수정자',
    `MODIFY_DATE`    DATETIME NOT NULL COMMENT '수정일자',
    `STORE_NO`    VARCHAR(100) NOT NULL COMMENT '매장번호',
    PRIMARY KEY ( `CATEGORY_NO` )
) COMMENT = '카테고리';

ALTER TABLE `TCATEGORY` ADD CONSTRAINT `TCATEGORY_PK` PRIMARY KEY ( `CATEGORY_NO` );

CREATE TABLE `TINDEREASON`
(
    `IN_DE_REASON_NO`    VARCHAR(100) NOT NULL COMMENT '증감사유번호',
    `IN_DE_REASON`    VARCHAR(100) NOT NULL COMMENT '증감사유',
    `INSERT_ID`    VARCHAR(100) NOT NULL COMMENT '등록자',
    `INSERT_DATE`    DATETIME NOT NULL COMMENT '등록일자',
    `MODIFY_ID`    VARCHAR(100) NOT NULL COMMENT '수정자',
    `MODIFY_DATE`    DATETIME NOT NULL COMMENT '수정일자',
    PRIMARY KEY ( `IN_DE_REASON_NO` )
) COMMENT = '증감사유';

ALTER TABLE `TINDEREASON` ADD CONSTRAINT `TINDEREASON_PK` PRIMARY KEY ( `IN_DE_REASON_NO` );

CREATE TABLE `TINGREDIENT`
(
    `INGREDIENT_NO`    VARCHAR(100) NOT NULL COMMENT '재료번호',
    `INGREDIENT_NAME`    VARCHAR(100) NOT NULL COMMENT '재료명',
    `QUANTITY`    DECIMAL NOT NULL COMMENT '재고',
    `INSERT_ID`    VARCHAR(100) NOT NULL COMMENT '등록자',
    `INSERT_DATE`    DATETIME NOT NULL COMMENT '등록일자',
    `MODIFY_ID`    VARCHAR(100) NOT NULL COMMENT '수정자',
    `MODIFY_DATE`    DATETIME NOT NULL COMMENT '수정일자',
    `STORE_NO`    VARCHAR(100) NOT NULL COMMENT '매장번호',
    PRIMARY KEY ( `INGREDIENT_NO`,`STORE_NO` )
) COMMENT = '재료';

ALTER TABLE `TINGREDIENT` ADD CONSTRAINT `TINGREDIENT_PK` PRIMARY KEY ( `INGREDIENT_NO`,`STORE_NO` );

CREATE TABLE `TINGREDIENTHIS`
(
    `IN_DE_QUANTITY`    DECIMAL NOT NULL COMMENT '증감량',
    `INSERT_ID`    VARCHAR(100) NOT NULL COMMENT '등록자',
    `INSERT_DATE`    DATETIME NOT NULL COMMENT '등록일자',
    `INGREDIENT_SEQ`    VARCHAR(100) NOT NULL COMMENT '재료순번',
    `EXPIRATION_DATE`    VARCHAR(100) NOT NULL COMMENT '유통기한',
    `INGREDIENT_NO`    VARCHAR(100) NOT NULL COMMENT '재료번호',
    `MODIFY_ID`    VARCHAR(100) NOT NULL COMMENT '수정자',
    `MODIFY_DATE`    DATETIME NOT NULL COMMENT '수정일자',
    `IN_DE_REASON_NO`    VARCHAR(100) NOT NULL COMMENT '증감사유번호',
    `STORE_NO`    VARCHAR(100) NOT NULL COMMENT '매장번호',
    PRIMARY KEY ( `INGREDIENT_NO`,`INGREDIENT_SEQ`,`STORE_NO` )
) COMMENT = '재료 내역';

ALTER TABLE `TINGREDIENTHIS` ADD CONSTRAINT `TINGREDIENTHIS_PK` PRIMARY KEY ( `INGREDIENT_NO`,`INGREDIENT_SEQ`,`STORE_NO` );

CREATE TABLE `TMENU`
(
    `MENU_NO`    VARCHAR(100) NOT NULL COMMENT '메뉴번호',
    `MENU_NAME`    VARCHAR(100) NOT NULL COMMENT '메뉴이름',
    `CATEGORY_NO`    VARCHAR(100) NOT NULL COMMENT '카테고리번호',
    `IMAGE_SAVE_NAME`    VARCHAR(100) NOT NULL COMMENT '이미지 저장명',
    `IMAGE_ORIGIN_NAME`    VARCHAR(100) NOT NULL COMMENT '이미지 원본명',
    `IMAGE_PATH`    VARCHAR(100) NOT NULL COMMENT '이미지 경로',
    `IMAGE_EXT`    VARCHAR(100) NOT NULL COMMENT '이미지 확장자',
    `INSERT_ID`    VARCHAR(100) NOT NULL COMMENT '등록자',
    `INSERT_DATE`    DATETIME NOT NULL COMMENT '등록일자',
    `MODIFY_ID`    VARCHAR(100) NOT NULL COMMENT '수정자',
    `MODIFY_DATE`    DATETIME NOT NULL COMMENT '수정일자',
    `SALE_STATUS_NO`    VARCHAR(100) NOT NULL COMMENT '판매상태번호',
    PRIMARY KEY ( `MENU_NO` )
) COMMENT = '메뉴';

ALTER TABLE `TMENU` ADD CONSTRAINT `TMENU_PK` PRIMARY KEY ( `MENU_NO` );

CREATE TABLE `TMENUINGREDIENT`
(
    `INGREDIENT_NO`    VARCHAR(100) NOT NULL COMMENT '재료번호',
    `MENU_NO`    VARCHAR(100) NOT NULL COMMENT '메뉴번호',
    `INSERT_ID`    VARCHAR(100) NOT NULL COMMENT '등록자',
    `INSERT_DATE`    DATETIME NOT NULL COMMENT '등록일자',
    `MODIFY_ID`    VARCHAR(100) NOT NULL COMMENT '수정자',
    `MODIFY_DATE`    DATETIME NOT NULL COMMENT '수정일자',
    `STORE_NO`    VARCHAR(100) NOT NULL COMMENT '매장번호',
    `USE_QUANTITY`    DECIMAL NOT NULL COMMENT '사용량',
    PRIMARY KEY ( `INGREDIENT_NO`,`MENU_NO`,`STORE_NO` )
) COMMENT = '메뉴재료';

ALTER TABLE `TMENUINGREDIENT` ADD CONSTRAINT `TMENUINGREDIENT_PK` PRIMARY KEY ( `INGREDIENT_NO`,`MENU_NO`,`STORE_NO` );

CREATE TABLE `TMENUPRICE`
(
    `MENU_NO`    VARCHAR(100) NOT NULL COMMENT '메뉴번호',
    `MENU_SEQ`    VARCHAR(100) NOT NULL COMMENT '메뉴순번',
    `SALE_PRICE`    VARCHAR(100) NOT NULL COMMENT '메뉴가격',
    `INSERT_ID`    VARCHAR(100) NOT NULL COMMENT '등록자',
    `INSERT_DATE`    DATETIME NOT NULL COMMENT '등록일자',
    `MODIFY_ID`    VARCHAR(100) NOT NULL COMMENT '수정자',
    `MODIFY_DATE`    DATETIME NOT NULL COMMENT '수정일자',
    PRIMARY KEY ( `MENU_NO`,`MENU_SEQ` )
) COMMENT = '메뉴 가격';

ALTER TABLE `TMENUPRICE` ADD CONSTRAINT `TMENUPRICE_PK` PRIMARY KEY ( `MENU_NO`,`MENU_SEQ` );

CREATE TABLE `TOPENCLOSE`
(
    `OPEN_CLOSE_NO`    VARCHAR(100) NOT NULL COMMENT '오픈마감번호',
    `INSERT_ID`    VARCHAR(100) NOT NULL COMMENT '등록자',
    `INSERT_DATE`    DATETIME NOT NULL COMMENT '등록일자',
    `FIFTY_THOUS`    DECIMAL COMMENT '마감오만원권',
    `TEN_THOUS`    DECIMAL COMMENT '마감만원권',
    `FIVE_THOUS`    DECIMAL COMMENT '마감오천원권',
    `ONE_THOUS`    DECIMAL COMMENT '마감천원권',
    `FIVE_HUN`    DECIMAL(10,0) COMMENT '마감오백원권',
    `ONE_HUN`    DECIMAL COMMENT '마감백원권',
    `FIFTY`    DECIMAL COMMENT '마감오십원권',
    `TEN`    DECIMAL COMMENT '마감십원',
    `CLOSE_MONEY`    DECIMAL COMMENT '마감현금시재',
    `OPEN_CLOSE_SEQ`    VARCHAR(100) NOT NULL COMMENT '오픈마감순번',
    `OPEN_MONEY`    DECIMAL NOT NULL COMMENT '개점준비금',
    `MODIFY_ID`    VARCHAR(100) NOT NULL COMMENT '수정자',
    `MODIFY_DATE`    DATETIME NOT NULL COMMENT '수정일자',
    `STORE_NO`    VARCHAR(100) NOT NULL COMMENT '매장번호',
    PRIMARY KEY ( `OPEN_CLOSE_NO`,`STORE_NO` )
) COMMENT = '오픈 마감';

ALTER TABLE `TOPENCLOSE` ADD CONSTRAINT `TOPENCLOSE_PK` PRIMARY KEY ( `OPEN_CLOSE_NO`,`STORE_NO` );

CREATE TABLE `TORDER`
(
    `MENU_NO`    VARCHAR(100) NOT NULL COMMENT '메뉴번호',
    `SALE_PRICE`    VARCHAR(100) NOT NULL COMMENT '판매가격',
    `QUANTITY`    DECIMAL NOT NULL COMMENT '수량',
    `DISCOUNT_PRICE`    VARCHAR(100) NOT NULL COMMENT '할인가격',
    `ORDER_DATE`    DATETIME NOT NULL COMMENT '주문시간',
    `CANCLE_DATE`    DATETIME COMMENT '취소시간',
    `INSERT_ID`    VARCHAR(100) NOT NULL COMMENT '등록자',
    `INSERT_DATE`    DATETIME NOT NULL COMMENT '등록일자',
    `MODIFY_ID`    VARCHAR(100) NOT NULL COMMENT '수정자',
    `MODIFY_DATE`    DATETIME NOT NULL COMMENT '수정일자',
    `FULL_PRICE_YN`    CHAR NOT NULL COMMENT '전체금액할인여부',
    `FULL_PER_YN`    CHAR NOT NULL COMMENT '전제비율할인여부',
    `SEL_PRICE_YN`    CHAR NOT NULL COMMENT '선택금액할인여부',
    `SEL_PER_YN`    CHAR NOT NULL COMMENT '선택비율할인여부',
    `SERVICE_YN`    CHAR NOT NULL COMMENT '서비스여부',
    `ORDER_SEQ`    VARCHAR(100) NOT NULL COMMENT '주문순번',
    `ORDER_STATUS_NO`    VARCHAR(100) NOT NULL COMMENT '주문상태번호',
    `TOTAL_SALE_PRICE`    VARCHAR(100) NOT NULL COMMENT '총 판매가격',
    `ORDER_NO`    VARCHAR(100) NOT NULL COMMENT '주문번호',
    `STORE_NO`    VARCHAR(100) NOT NULL COMMENT '매장번호',
    `TABLE_NO`    VARCHAR(100) NOT NULL COMMENT '테이블번호',
    PRIMARY KEY ( `ORDER_NO`,`ORDER_SEQ`,`STORE_NO` )
) COMMENT = '주문';

ALTER TABLE `TORDER` ADD CONSTRAINT `TORDER_PK` PRIMARY KEY ( `ORDER_NO`,`ORDER_SEQ`,`STORE_NO` );

CREATE TABLE `TORDERSTATUS`
(
    `ORDER_STATUS_NO`    VARCHAR(100) NOT NULL COMMENT '주문상태번호',
    `ORDER_STATUS`    VARCHAR(100) NOT NULL COMMENT '주문상태',
    `INSERT_ID`    VARCHAR(100) NOT NULL COMMENT '등록자',
    `INSERT_DATE`    DATETIME NOT NULL COMMENT '등록일자',
    `MODIFY_ID`    VARCHAR(100) NOT NULL COMMENT '수정자',
    `MODIFY_DATE`    DATETIME NOT NULL COMMENT '수정일자',
    PRIMARY KEY ( `ORDER_STATUS_NO` )
) COMMENT = '주문상태';

ALTER TABLE `TORDERSTATUS` ADD CONSTRAINT `TORDERSTATUS_PK` PRIMARY KEY ( `ORDER_STATUS_NO` );

CREATE TABLE `TSALESTATUS`
(
    `SALE_STATUS_NO`    VARCHAR(100) NOT NULL COMMENT '판매상태번호',
    `SALE_STATUS`    VARCHAR(100) NOT NULL COMMENT '판매상태',
    `INSERT_ID`    VARCHAR(100) NOT NULL COMMENT '등록자',
    `INSERT_DATE`    DATETIME NOT NULL COMMENT '등록일자',
    `MODIFY_ID`    VARCHAR(100) NOT NULL COMMENT '수정자',
    `MODIFY_DATE`    DATETIME NOT NULL COMMENT '수정일자',
    PRIMARY KEY ( `SALE_STATUS_NO` )
) COMMENT = '판매상태';

ALTER TABLE `TSALESTATUS` ADD CONSTRAINT `TSALESTATUS_PK` PRIMARY KEY ( `SALE_STATUS_NO` );

CREATE TABLE `TSTORE`
(
    `STORE_NO`    VARCHAR(100) NOT NULL COMMENT '매장번호',
    `STORE_NAME`    VARCHAR(100) NOT NULL COMMENT '매장명',
    `INSERT_ID`    VARCHAR(100) NOT NULL COMMENT '등록자',
    `INSERT_DATE`    DATETIME NOT NULL COMMENT '등록일자',
    `MODIFY_ID`    VARCHAR(100) NOT NULL COMMENT '수정자',
    `MODIFY_DATE`    DATETIME NOT NULL COMMENT '수정일자',
    `USE_YN`    VARCHAR(100) NOT NULL COMMENT '사용유무',
    PRIMARY KEY ( `STORE_NO` )
) COMMENT = '매장';

ALTER TABLE `TSTORE` ADD CONSTRAINT `TSTORE_PK` PRIMARY KEY ( `STORE_NO` );

CREATE TABLE `TTABLE`
(
    `TABLE_NO`    VARCHAR(100) NOT NULL COMMENT '테이블번호',
    `TABLE_NAME`    VARCHAR(100) NOT NULL COMMENT '테이블명',
    `INSERT_ID`    VARCHAR(100) NOT NULL COMMENT '등록자',
    `INSERT_DATE`    DATETIME NOT NULL COMMENT '등록일자',
    `MODIFY_ID`    VARCHAR(100) NOT NULL COMMENT '수정자',
    `MODIFY_DATE`    DATETIME NOT NULL COMMENT '수정일자',
    `USE_YN`    CHAR NOT NULL COMMENT '사용여부',
    `STORE_NO`    VARCHAR(100) NOT NULL COMMENT '매장번호',
    PRIMARY KEY ( `STORE_NO`,`TABLE_NO` )
) COMMENT = '테이블';

ALTER TABLE `TTABLE` ADD CONSTRAINT `TTABLE_PK` PRIMARY KEY ( `STORE_NO`,`TABLE_NO` );

CREATE TABLE `TUSER`
(
    `USER_NO`    VARCHAR(100) NOT NULL COMMENT '사용자번호',
    `USER_NAME`    VARCHAR(100) NOT NULL COMMENT '사용자명',
    `PHONE_NUM`    VARCHAR(100) NOT NULL COMMENT '핸드폰번호',
    `USE_YN`    CHAR NOT NULL COMMENT '사용유무',
    `INSERT_ID`    VARCHAR(100) NOT NULL COMMENT '등록자',
    `INSERT_DATE`    DATE NOT NULL COMMENT '등록일자',
    `MODIFY_ID`    VARCHAR(100) NOT NULL COMMENT '수정자',
    `MODIFY_DATE`    DATE NOT NULL COMMENT '수정일자',
    `STORE_NO`    VARCHAR(100) NOT NULL COMMENT '매장번호',
    `USER_ID`    VARCHAR(100) NOT NULL COMMENT '아이디',
    `PASSWORD`    VARCHAR(100) NOT NULL COMMENT '비밀번호',
    PRIMARY KEY ( `USER_NO` )
) COMMENT = '사용자';

ALTER TABLE `TUSER` ADD CONSTRAINT `TUSER_PK` PRIMARY KEY ( `USER_NO` );